sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t haakongv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true haakongv/react-test npm test

after_success:
  - docker build -t haakongv/multi-client ./client
  - docker build -t haakongv/multi-nginx ./nginx
  - docker build -t haakongv/multi-server ./server
  - docker build -t haakongv/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push haakongv/multi-client
  - docker push haakongv/multi-nginx
  - docker push haakongv/multi-server
  - docker push haakongv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-634386674446
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: $AWS_SECRET_KEY
